### ISSUE TITLE
Error with connection

### ISSUE THREAD

**Issue by technocon** [eventbrite/python_hive_utils#2]
Here is my code:

`import hive_utils`

`query = """`
    `SELECT sm.metric_name as 'DRC', sm.metric_value as value from sm`
    `WHERE sm.year = 2016`
    `AND sm.month = 5`
    `AND sm.tail = 10646`
    `AND sm.metric_name = 'DRC_kbps'`
    `limit 100`
`"""`

`hive_client = hive_utils.HiveClient(`
   `server=config['_I redacted the real server_'],`
   `port=config['8888'],`
   `db=config['analysis']`
`)`
`for row in hive_client.execute(query):`
   `print '%s: %s' % (row['DRC'], row['value'])`

I get the following error:

> rcates@RCates-MBP:~/Documents/Scripting> python connect.py 
> Traceback (most recent call last):
>   File "connect.py", line 14, in <module>
>     server=config['_I redacted the real server'_],
> NameError: name 'config' is not defined

Please Help

**Comment by ebpitts** [comment]
The sample code in the README assumes you defined your configuration in a dictionary. For example,

``` python
config = {
    'HOST': 'example.com',
    'PORT': 8888,
    'NAME': 'analysis',
}

hive_client = hive_utils.HiveClient(
    server=config['HOST'],
    port=config['PORT'],
    db=config['NAME'],
)
```

would work.

If you want to pass the config values in directly, just do

``` python
hive_client = hive_utils.HiveClient(
    server='_I redacted the real server_',
    port=8888,
    db='analysis',
)
```

**Comment by technocon** [comment]
It would be helpful if you would specify that in the README, it is not intuitive. Just a thought.
